apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "<to be filled in deploy_to_kubernetes script>"
  name: laa-cla-public
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: laa-cla-public-app
        env: production
        service_area: laa-get-access
        service_team: cla-fala
    spec:
      containers:
      - image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-get-access/laa-cla-public:master
        name: app
        readinessProbe:
          httpGet:
            path: /ping.json
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping.json
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
        ports:
        - containerPort: 80
          name: http
        env:
        - name: CLA_ENV
          value: prod
        - name: BACKEND_BASE_URI
          value: https://fox.civillegaladvice.service.gov.uk
        - name: LAALAA_API_HOST
          value: https://prod.laalaa.dsd.io
        - name: LOG_LEVEL
          value: INFO
        - name: GA_ID
          value: UA-37377084-21
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: clasecret
              key: flask_secret_key
        - name: OS_PLACES_API_KEY
          valueFrom:
            secretKeyRef:
              name: os-places
              key: apiKey
