forms:

  ProblemForm:
    fields:

      categories:
        field_options:
          violence:
            selected_notification: Os ydych mewn perygl uniongyrchol, gallwch ofyn i ni [eich ffonio’n ôl](/call-me-back).

          family:
            selected_notification: Os ydych yn rhiant i blentyn y mae’r awdurdod lleol yn ceisio ei ddwyn i’w gofal, gofynnwch i ni [eich ffonio’n ôl](/call-me-back).

  AboutYouForm:
    fields:

      have_children:
        more_info: >
          Dylech gynnwys pobl ifanc 16 oed neu hŷn sy’n byw gyda chi a’ch bod yn eu cynnal yn ariannol yn y cwestiwn nesaf o dan “Oes gennych unrhyw ddibynyddion sy’n 16 oed neu hŷn?”

  PropertyForm:
    fields:
      in_dispute:
        more_info: >
          A disputed property is one whose ownership is disputed by someone eg an ex-partner wants
          to claim a share in it as part of a divorce or separation, or a creditor or mortgage
          company wants to force the sale of it to repay a debt.
