forms:

  ProblemForm:
    fields:

      categories:
        field_options:
          violence:
            selected_notification: Os ydych mewn perygl uniongyrchol, gallwch ofyn i ni [eich ffonio’n ôl](/call-me-back).

          family:
            selected_notification: Os ydych yn rhiant i blentyn y mae’r awdurdod lleol yn ceisio ei ddwyn i’w gofal, gofynnwch i ni [eich ffonio’n ôl](/call-me-back).

  AboutYouForm:
    fields:

      have_children:
        more_info: >
          Dylech gynnwys pobl ifanc 16 oed neu hŷn sy’n byw gyda chi a’ch bod yn eu cynnal yn ariannol yn y cwestiwn nesaf o dan “Oes gennych unrhyw ddibynyddion sy’n 16 oed neu hŷn?”

  PropertyForm:
    fields:
      in_dispute:
        more_info: >
          Eiddo sy’n destun dadl yw lle mae rhywun yn dadlau dros ei berchnogaeth e.e. cyn partner sydd eisiau hawlio cyfran fel rhan o ysgariad neu wahaniad, neu gredydwr neu gwmni morgais sydd eisiau gorfodi gwerthiant er mwyn talu dyled.
