forms:

  ProblemForm:
    fields:

      categories:
        field_options:
          violence:
            selected_notification: If you are in imediate danger you can ask us to [call you back](/call-me-back).

          housing:
            selected_notification: If you are in imediate need of housing you can ask us to [call you back](/call-me-back).

  AboutYouForm:
    fields:

      have_children:
        more_info: >
          Young people aged 16 or over who live with you and who you support financially should
          be included in the next question under “Do you have any dependants aged 16 or over?”

      have_dependants:
        more_info: This could be a young person for whom you get Child Benefit

      have_valuables:
        more_info: |
          Don’t include the following:

          - household furniture and effects, unless they’re exceptionally valuable
          - tools of your trade (for example, computers for a graphic designer, carpentry tools for a carpenter)
          - the car or vehicle you use regularly, unless it’s a classic car or luxury vehicle

          Give the item’s current value - what the item would sell for if you sold it today.

  PropertyForm:
    fields:
      in_dispute:
        more_info: >
          A disputed property is one whose ownership is disputed by someone eg an ex-partner wants
          to claim a share in it as part of a divorce or separation, or a creditor or mortgage
          company wants to force the sale of it to repay a debt.

  SavingsForm:
    fields:
      valuables:
        more_info: |
          Don’t include the following:

          - household furniture and effects, unless they’re exceptionally valuable
          - tools of your trade (for example, computers for a graphic designer, carpentry tools for a carpenter)
          - the car or vehicle you use regularly, unless it’s a classic car or luxury vehicle

          Give the item’s current value - what the item would sell for if you sold it today.
