apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laa-cla-public
spec:
  template:
    metadata:
      labels:
        app: laa-cla-public-app
    spec:
      containers:
      - image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-get-access/laa-cla-public:master
        name: app
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ENV
          value: staging
        - name: BACKEND_BASE_URI
          value: https://staging-backend.cla.dsd.io/
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: clasecret
              key: flask_secret_key
